<?php 
date_default_timezone_set("Asia/Singapore");
    require 'getData/connection.php';
    require_once 'dompdf/lib/html5lib/Parser.php';
    require_once 'dompdf/lib/php-font-lib/src/FontLib/Autoloader.php';
    require_once 'dompdf/lib/php-svg-lib/src/autoload.php';
    require_once 'dompdf/src/Autoloader.php';
    Dompdf\Autoloader::register();
    // reference the Dompdf namespace
    use Dompdf\Dompdf;

    // instantiate and use the dompdf class
    $dompdf = new Dompdf();
    $at = $_GET['at'];
    $datetime = date("Y-m-d h:i A");

    $sel = mysqli_query($conn,"SELECT *, CONCAT(Firstname, ' ' ,MiddleName, ' ', LastName) AS Fullname FROM nurses WHERE NurseID ='$at'");

    while ($row = mysqli_fetch_assoc($sel)) {
        $genfullname = $row['Fullname'];
    }

     if(isset($_GET['searchparam'])){
         $searchparam = $_GET['searchparam'];
         $query = mysqli_query($conn,"SELECT patient_diet.Diet , patient_diet.DietRemarks , medical_details.BedID , CONCAT(patients.FirstName, ' ' , patients.MiddleName , ' ', patients.LastName) AS Fullname
         FROM patient_diet
         JOIN medical_details 
         JOIN patients
         WHERE patient_diet.MedicalID = medical_details.MedicalID AND medical_details.AdmissionID = patients.AdmissionID AND patients.AdmissionType = 'Inpatient'");
     }else{
         $query = mysqli_query($conn,"SELECT patient_diet.Diet , patient_diet.DietRemarks , medical_details.BedID , CONCAT(patients.FirstName, ' ' , patients.MiddleName , ' ', patients.LastName) AS Fullname
         FROM patient_diet
         JOIN medical_details 
         JOIN patients
         WHERE patient_diet.MedicalID = medical_details.MedicalID AND medical_details.AdmissionID = patients.AdmissionID AND patients.AdmissionType = 'Inpatient'");
     }
    
    $html = '<link type="text/css" href="assets/plugins/gridforms/gridforms/gridforms.css" rel="stylesheet">
    <style>
    table {
        font-family: arial, sans-serif;
        border-collapse: collapse;
        width: 100%;
    }

    td, th {
        border: 1px solid #dddddd;
        text-align: left;
        padding: 8px;
    }

    tr:nth-child(even) {
        background-color: #dddddd;
    }

    h4 {
        font-family: arial, sans-serif;
    }
    </style>
    

    <head> 
    <style>
    #footer { position: fixed; center: 0px; bottom: -150px; right: 0px; height: 150px; background-color: #F4F4F4; }
    #footer .page:after { content: counter(page, upper-roman); }
    </style>

    <img src="assets/img/report-header.jpg">
    <h4><center>Patient Diet</center></h4>
    </head>
    <div class="container-fluid">
    <br>
            <table>
            <tr>
                <th>Room & Bed No.</th>
                <th>Fullname</th>
                <th>Diet</th>
                <th>Diet Remarks</th>
            </tr>';
    
         while ($row = mysqli_fetch_assoc($query)) {
         $bedid = $row['BedID'];
         $fullname = $row['Fullname'];
         $diet = $row['Diet'];
         $dietremarks = $row['DietRemarks'];
    
         $html .= '<tr>
          <td>' . $bedid . ' </td><td>' . $fullname . '</td><td>' . $diet . '</td><td>' . $dietremarks . '</td> </tr>';
        }
    
    $html .= '</table>
        </div>
        <div id="footer">
        Generated by:   '.$genfullname.' 
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        Generated on: '.$datetime.'
        </div>
    ';

    $dompdf->loadHtml($html);   

    // (Optional) Setup the paper size and orientation
    $dompdf->setPaper('A4', 'potrait');

    // Render the HTML as PDF
    $dompdf->render();

    // Output the generated PDF (1 = download and 0 = preview)
    $dompdf->stream("PatientsReport",array("Attachment"=>0));

?>