
<?php 
    require 'getData/connection.php';
    require_once 'dompdf/lib/html5lib/Parser.php';
    require_once 'dompdf/lib/php-font-lib/src/FontLib/Autoloader.php';
    require_once 'dompdf/lib/php-svg-lib/src/autoload.php';
    require_once 'dompdf/src/Autoloader.php';
    Dompdf\Autoloader::register();

    use Dompdf\Dompdf;

    $dompdf = new Dompdf();

    $at = $_GET['at'];
   
    $search =  isset($_GET['param']) ? $_GET['param'] : '';
  
    $datetime = date("Y-m-d h:i A");

 

    if($search != ''){
        $param =  explode(' - ',$search); 
        $cnt = count($param);
        for($x = 0; $x < $cnt; $x++){
            if($x == 0){
                $start = $param[$x];
            }else{
                $end = $param[$x];
            }
        }

        $filter = $start . ' - ' . $end;
    }else{
        $filter = 'None';
    }
    

    switch ($at[0]) {
        case '7':
        $sel = mysqli_query($conn,"SELECT *, CONCAT(Firstname, ' ' ,MiddleName, ' ', LastName) AS Fullname FROM secretary WHERE SecretaryID ='$at'");

        while ($row = mysqli_fetch_assoc($sel)) {
            $genfullname = $row['Fullname'];
        }
        break;
        
        default:
        $sel = mysqli_query($conn,"SELECT *, CONCAT(Firstname, ' ' ,MiddleName, ' ', LastName) AS Fullname FROM admin WHERE AdminID ='$at'");

        while ($row = mysqli_fetch_assoc($sel)) {
            $genfullname = $row['Fullname'];
        }
        break;
    }


    $query2 = mysqli_query($conn,"SELECT a.AdmissionID,a.CompleteAddress,a.latcoor,a.longcoor,b.MedicalID,b.AdmissionID,c.Conditions,( SELECT COUNT(Conditions) FROM medical_conditions WHERE Conditions = c.Conditions) AS count FROM patients a,medical_details b, conditions c, medical_conditions d WHERE a.AdmissionID = b.AdmissionID AND b.MedicalID = d.MedicalID AND c.Conditions = d.Conditions");


    $html = '
    <link type="text/css" href="assets/plugins/gridforms/gridforms/gridforms.css" rel="stylesheet">
    <style>
    table {
        font-family: arial, sans-serif;
        border-collapse: collapse;
        width: 100%;
    }

    td, th {
        border: 1px solid #dddddd;
        text-align: left;
        padding: 8px;
    }

    tr:nth-child(even) {
        background-color: #dddddd;
    }

    h4,h5 {
        font-family: arial, sans-serif;
    }
    </style>
    

    <head> 
    <style>
    #footer { position: fixed; center: 0px; bottom: -150px; right: 0px; height: 150px; background-color: #F4F4F4; }
    #footer .page:after { content: counter(page, upper-roman); }
    </style>

    <img src="assets/img/report-header.jpg">    
    <h4><center>Common Illnesses Report</center></h4>
    <h5><center>Filter: '.$filter.'</center></h5>
    </head>
    <div class="container-fluid">
    <br>
      
            <table>
            <tr>
                <th>Admission ID</th>
                <th>Complete Address</th>
                <th>Conditions</th>
            </tr>';
    
        while ($row = mysqli_fetch_assoc($query2)) {
         $admissionid = $row['AdmissionID'];
         $complete = $row['CompleteAddress'];
         $conditions = $row['Conditions'];
    
         $html .= '<tr>
          <td> ' . $admissionid . ' </td><td>' . $complete . '</td><td>' . $conditions . '</td></tr>';
        }
    
    
    $html .= '</table>
        </div>
        <div id="footer">
        Generated by:   '.$genfullname.' 
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        Generated on: '.$datetime.'
        </div>
        ';
        
    $dompdf->loadHtml($html);   

    // (Optional) Setup the paper size and orientation
    $dompdf->setPaper('A4', 'potrait');

    // Render the HTML as PDF
    $dompdf->render();

    // Output the generated PDF (1 = download and 0 = preview)
    $dompdf->stream("IllnessesReport",array("Attachment"=>0));

    ?>