
<?php 
    require 'getData/connection.php';
    require_once 'dompdf/lib/html5lib/Parser.php';
    require_once 'dompdf/lib/php-font-lib/src/FontLib/Autoloader.php';
    require_once 'dompdf/lib/php-svg-lib/src/autoload.php';
    require_once 'dompdf/src/Autoloader.php';
    Dompdf\Autoloader::register();

    use Dompdf\Dompdf;

    $dompdf = new Dompdf();

    $at = $_GET['at'];
    $id = $_GET['id'];

    $datetime = date("Y-m-d h:i A");

    $cnt = 1;

    switch ($at[0]) {
            case '2':
            $sel = mysqli_query($conn,"SELECT *, CONCAT(Firstname, ' ' ,MiddleName, ' ', LastName) AS Fullname FROM admission_staffs WHERE AdmissionStaffID ='$at'");

            while ($row = mysqli_fetch_assoc($sel)) {
                $genfullname = $row['Fullname'];
            }
            break;

            case '4':
            $sel = mysqli_query($conn,"SELECT *, CONCAT(Firstname, ' ' ,MiddleName, ' ', LastName) AS Fullname FROM physicians WHERE PhysicianID ='$at'");

            while ($row = mysqli_fetch_assoc($sel)) {
                $genfullname = $row['Fullname'];
            }
            break;
            
            case '7':
            $sel = mysqli_query($conn,"SELECT *, CONCAT(Firstname, ' ' ,MiddleName, ' ', LastName) AS Fullname FROM secretary WHERE SecretaryID ='$at'");

            while ($row = mysqli_fetch_assoc($sel)) {
                $genfullname = $row['Fullname'];
            }
            break;
        
        default:
        $sel = mysqli_query($conn,"SELECT *, CONCAT(Firstname, ' ' ,MiddleName, ' ', LastName) AS Fullname FROM nurses WHERE NurseID ='$at'");

        while ($row = mysqli_fetch_assoc($sel)) {
            $genfullname = $row['Fullname'];
        }
        break;
    }
    


    $sel = mysqli_query($conn,"SELECT * FROM patients_archive WHERE ArchiveID = '$id'");


    $html = '
        <link type="text/css" href="assets/plugins/gridforms/gridforms/gridforms.css" rel="stylesheet">
        <style>
        table {
            font-family: arial, sans-serif;
            border-collapse: collapse;
            width: 100%;
        }

        td, th {
            border: 1px solid #dddddd;
            text-align: left;
            padding: 8px;
        }

        tr:nth-child(even) {
            background-color: #dddddd;
        }

        h4 {
            font-family: arial, sans-serif;
        }
        </style>
        
    
        <head> 
        <style>
        #footer { position: fixed; center: 0px; bottom: -150px; right: 0px; height: 150px; background-color: #F4F4F4; }
        #footer .page:after { content: counter(page, upper-roman); }
        </style>

        <img src="assets/img/report-header.jpg">
        <h4><center>Medical History Report</center></h4>
        </head>
        <div class="container-fluid">
        <br>
      
            <br>Medical History Goes Below:<br><br>
                <table>
                <tr>
                    <th>Admission ID</th>
                    <th>Admission Date</th>
                    <th>Admission Time</th>
                    <th>Admission Type</th>
                </tr>';
        
            while ($row = mysqli_fetch_assoc($sel)) {
             $ArchiveID = $row['ArchiveID'];
             $archivedate = $row['AdmissionDate'];
             $archivetime = $row['AdmissionTime'];
             $archivetype = $row['AdmissionType'];
        
             $html .= '<tr>
              <td> ' . $ArchiveID . ' </td><td>' . $archivedate . '</td><td>' . $archivetime . '</td><td>'. $archivetype . '</td></tr>';
            }
        
        
        $html .= '</table>
            </div>
            <div id="footer">
            Generated by:   '.$genfullname.' 
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            Generated on: '.$datetime.'
            </div>
            ';
        
    $dompdf->loadHtml($html);   

    // (Optional) Setup the paper size and orientation
    $dompdf->setPaper('A4', 'potrait');

    // Render the HTML as PDF
    $dompdf->render();

    // Output the generated PDF (1 = download and 0 = preview)
    $dompdf->stream("MedicationReport",array("Attachment"=>0));

    ?>